language: node_js
node_js:
  - "11"
before_install:
  - yarn global add gulp-cli
install:
  - yarn
script:
  - gulp build
  - chmod +x deploy.sh
  - ./deploy.sh
cache:
  yarn: true
  directories:
    - node_modules
